const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);let view='merchant';
function calc(){let amount=Math.max(0,+$('amount').value||0),route=$('route').value,merchant=$('merchant').value,cat=$('category').value,gst=$('gst').checked,count=Math.max(1,+$('count').value||1),fee=0,label='ZERO MDR',formula='No MDR under this treatment',note='',uncertain=false;
$('merchant').disabled=route!=='bank';$('category').disabled=route!=='bank'||merchant==='p2pm';
if(route==='p2p'){note='Person-to-person UPI remains free for payer and beneficiary.'}
else if(route==='autopay'){note='NPCI says prescribed MDR does not apply to UPI mandates / AutoPay.'}
else if(route==='credit'){label='SEPARATE RULES';note='Credit-card-on-UPI and credit lines follow separate credit-product pricing, not this 0.4% framework.'}
else if(merchant==='p2pm'){note='P2PM micro merchants remain at zero MDR, even when one payment exceeds ₹2,000. Confirm account classification with the acquirer.'}
else if(cat==='education'){label='CONFIRM WITH ACQUIRER';note='NPCI says education gets a flat-fee or capped treatment, but the FAQ does not publish one universal number. No estimate is shown.';uncertain=true}
else if(cat==='capital'){fee=Math.min(amount*.0002,300);label='CAPITAL · 0.02%';formula=`${fmt(amount)} × 0.02%, max ₹300`;note='Capital-market tier from the NPCI FAQ. The FAQ does not restate the ₹2,000 threshold for this tier.'}
else if(amount<=2000){note='Eligible P2M payments are zero-MDR up to and including ₹2,000.'}
else if(cat==='industry'){fee=5;label='INDUSTRY · ₹5 FLAT';formula='Flat ₹5 above ₹2,000';note='Rail, telecom, insurance, fuel and public utilities are explicitly named. Confirm the merchant category code.'}
else{fee=Math.min(amount*.004,300);label=amount>=75000?'STANDARD · ₹300 CAP':'STANDARD · 0.40%';formula=amount>=75000?'0.40% reaches the ₹300 ceiling':`${fmt(amount)} × 0.40%`;note=amount>=75000?'Standard P2M MDR is capped at ₹300 from ₹75,000.':'Standard direct-account P2M rate above ₹2,000.'}
const tax=gst?fee*.18:0,totalFee=fee+tax,net=amount-totalFee,recovery=Math.min(100,Math.max(0,+$('recovery').value||0)),indirect=totalFee*recovery/100;
$('recoveryText').textContent=`${recovery}% illustrated via general pricing`;$('fee').textContent=view==='consumer'?fmt(0):fmt(totalFee);$('resultKicker').textContent=view==='consumer'?'Direct consumer UPI charge':'Merchant cost per payment';$('treatment').textContent=label;$('formula').textContent=gst&&fee?formula+' + estimated GST':formula;$('customerPays').textContent=fmt(amount);$('net').textContent=uncertain?'Check contract':fmt(net);$('monthly').textContent=uncertain?'—':fmt(totalFee*count);$('rate').textContent=uncertain?'—':(amount?totalFee/amount*100:0).toFixed(3)+'%';
$('callout').innerHTML=view==='consumer'?`<b>You are charged ₹0 by UPI.</b><span>${recovery?`The merchant-side fee is ${fmt(totalFee)}. A ${recovery}% broad pricing-recovery illustration equals ${fmt(indirect)}, but NPCI prohibits adding MDR as a UPI surcharge.`:'A merchant may have a business cost, but NPCI prohibits passing MDR as a UPI charge.'}</span>`:`<b>${fee?'Merchant bears this cost.':'Zero MDR in this scenario.'}</b><span>${note}${gst&&fee?' GST is an estimate on the fee, not on the payment amount.':''}</span>`;}
$('amount').oninput=e=>{let v=Math.max(0,+e.target.value||0);$('amountRange').value=Math.min(100000,v);calc()};$('amountRange').oninput=e=>{$('amount').value=e.target.value;calc()};['route','merchant','category','gst','count','recovery'].forEach(id=>$(id).oninput=calc);document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('amount').value=b.dataset.amt;$('amountRange').value=b.dataset.amt;calc()});document.querySelectorAll('.mode button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.mode button').forEach(x=>x.classList.toggle('active',x===b));calc()});calc();
